openapi: 3.0.0
info:
  title: Product API
  description: API для управления продуктами и заказами
  version: 1.0.0
servers:
  - url: https://67e3044497fc65f535387590.mockapi.io/api
paths:
  /products:
    get:
      summary: Получить список продуктов
      responses:
        200:
          description: Успешный ответ
        404:
          description: Продукты не найдены
    post:
      summary: Создать продукт
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, description, price, quantity]
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  minimum: 0
                quantity:
                  type: integer
                  minimum: 1
      responses:
        201:
          description: Продукт создан
        400:
          description: Неверные данные
  /products/{id}:
    get:
      summary: Получить продукт по ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Успешный ответ
        404:
          description: Продукт не найден
    put:
      summary: Обновить продукт (полная замена)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, description]
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        200:
          description: Успешное обновление
        400:
          description: Неверные данные
    delete:
      summary: Удалить продукт
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Удалено успешно
        404:
          description: Продукт не найден
