openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API для управления продуктами

components:
  securitySchemes:
    bearerAuth:            # можно использовать другой способ авторизации
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор продукта
          readOnly: true
        name:
          type: string
          description: Название продукта
        description:
          type: string
          description: Описание продукта
        price:
          type: number
          format: float
          description: Цена продукта
        quantity:
          type: integer
          description: Количество на складе
      required:
        - name
        - description
        - price
        - quantity

    Order:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор заказа
          readOnly: true
        customer_name:
          type: string
          description: Имя заказчика
        customer_email:
          type: string
          format: email
          description: Email заказчика
        customer_address:
          type: string
          description: Адрес заказчика
        order_details:
          type: string
          description: Детали заказа

    ProductPatch:
      type: object
      properties:
        name:
          type: string
          description: Название продукта (для обновления)
        description:
          type: string
          description: Описание продукта (для обновления)
        price:
          type: number
          format: float
          description: Цена продукта (для обновления)
        quantity:
          type: integer
          description: Количество на складе (для обновления)

paths:
  /api/products:
    get:
      summary: Получить список продуктов
      responses:
        '200':
          description: Список продуктов успешно возвращен.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Некорректный запрос
        '404':
          description: Продукты не найдены
    post:
      security:
        - bearerAuth: []  # Требуется авторизация
      summary: Создать продукт
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Продукт успешно создан
        '400':
          description: Некорректные данные в запросе
        '401':
          description: Unauthorized
        '500':
          description: Ошибка сервера

  /api/products/{id}:
    get:
      summary: Получить продукт по ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Идентификатор продукта
      responses:
        '200':
          description: Успешное получение данных продукта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Некорректный запрос
        '401':
          description: Unauthorized
        '404':
          description: Продукт не найден
    put:
      security:
        - bearerAuth: []  # Требуется авторизация
      summary: Обновить продукт по ID (полная замена)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Идентификатор продукта
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Продукт успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Некорректные данные в запросе
        '401':
          description: Unauthorized
        '404':
          description: Продукт не найден
        '500':
          description: Ошибка сервера
    delete:
      security:
        - bearerAuth: []  # Требуется авторизация
      summary: Удалить продукт по ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Идентификатор продукта
      responses:
        '200':
          description: Продукт успешно удален
        '400':
          description: Некорректный запрос
        '401':
          description: Unauthorized
        '404':
          description: Продукт не найден
    patch:
      security:
        - bearerAuth: []  # Требуется авторизация
      summary: Частичное обновление продукта по ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Идентификатор продукта
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductPatch'
      responses:
        '200':
          description: Продукт успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Некорректный запрос
        '401':
          description: Unauthorized
        '404':
          description: Продукт не найден

  /api/orders:
    post:
      summary: Создать заказ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Заказ успешно создан
        '400':
          description: Некорректные данные в запросе
        '401':
          description: Unauthorized
